variables:
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY}/${CI_PROJECT_PATH}

stages:
  - build_image
  - deploy

Image:
  stage: build_image
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${CONTAINER_IMAGE_LATEST}:${CI_COMMIT_SHORT_SHA} --file Dockerfile .
    - docker push ${CONTAINER_IMAGE_LATEST}:${CI_COMMIT_SHORT_SHA}
  only:
    - master

argocd-deploy:
  image: argoproj/argocd:v1.8.7
  stage: deploy
  environment:
    name: development
  variables:
    APP: orao-fastgateway
  script:
    - export ARGOCD_SERVER=argo-dev.orao.network
    - export ARGOCD_AUTH_TOKEN=${ARGOCD_TOKEN}
    - argocd app set $APP --helm-set image.tag=${CI_COMMIT_SHORT_SHA} --helm-set image.repository=${CONTAINER_IMAGE_LATEST} --grpc-web
    - argocd app sync $APP --force --grpc-web || true
  only:
    - master
    - tags
